version: '3.8'

services:
  dev:
    build:
      context: .
      target: development-stage
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

  prod:
    build:
      context: .
    ports:
      - "80:80"
